//
//  ContentView.swift
//
//  This file is automatically generated by akidon0000/XprojGen
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "globe")
                .imageScale(.large)
                .foregroundStyle(.tint)
            Text("Hello, world! Meguri")
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
