//
//  MeguriApp.swift
//
//  This file is automatically generated by akidon0000/XprojGen
//

import SwiftUI

@main
struct MeguriApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
